require 'optparse'
require 'json'
require 'tsort'

require_relative 'circuit_sim/application'
require_relative 'circuit_sim/gates'
require_relative 'circuit_sim/builder'
require_relative 'circuit_sim/circuit'
require_relative 'circuit_sim/pin'
require_relative 'circuit_sim/truth_table'
